SELECT
     KCU1.CONSTRAINT_NAME AS CONSTRAINT_NAME 
    ,KCU1.TABLE_SCHEMA AS TABLE_SCHEMA
	,KCU1.TABLE_NAME AS TABLE_NAME
    ,KCU1.COLUMN_NAME AS COLUMN_NAME 
FROM
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS Tab, 
    INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE KCU1 
WHERE 
    KCU1.Constraint_Name = Tab.Constraint_Name
    AND KCU1.Table_Name = Tab.Table_Name
	AND Constraint_Type = 'PRIMARY KEY';