// --------------------------------------------------------------------------------------------------------------------
// <copyright file="PortScannerTests.cs" company="Ryan Penfold">
//   Copyright © Ryan Penfold. All rights reserved.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

using RyanPenfold.Utilities.Net;

namespace RyanPenfold.Utilities.Tests.Unit.Net.Mail
{
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    /// <summary>
    /// Provides unit tests for the 
    /// <see cref="PortScanner" /> class.
    /// </summary>
    [TestClass]
    public class PortScannerTests
    {
        /// <summary>
        /// Tests the Scan method of the
        /// <see cref="PortScanner" /> class.
        /// </summary>
        [TestMethod]
        public void Scan()
        {
            // The amount of time to make a scan
            long milliseconds;

            // Create a new stopwatch
            var stopWatch = new System.Diagnostics.Stopwatch();

            // Start the stopwatch
            stopWatch.Start();

            // Call the scan method
            var result = PortScanner.Scan(string.Empty, 0, out milliseconds);

            // Stop the stopwatch
            stopWatch.Stop();

            // The result should be false
            Assert.IsFalse(result);

            // Local time should elapsed should be greater than the completion time generated by the method
            Assert.IsTrue(stopWatch.ElapsedMilliseconds >= milliseconds);
        }
    }
}